# Generated by Django 3.2.16 on 2025-04-28 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250428_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='textarea',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 17, 44, 55, 38984, tzinfo=utc), help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', verbose_name='Дата и время публикации'),
        ),
    ]
